# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Velocity Controllers ---------------------------------------
wheel0_motor_shaft_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel0_motor_shaft_joint
  pid: {p: 0.05,i: 0.0,d: 0.0001, i_clamp: 1.0, antiwindup: true}
wheel1_motor_shaft_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel1_motor_shaft_joint
  pid: {p: 0.05,i: 0.0,d: 0.0001, i_clamp: 1.0, antiwindup: true}
wheel2_motor_shaft_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel2_motor_shaft_joint
  pid: {p: 0.05,i: 0.0,d: 0.0001, i_clamp: 1.0, antiwindup: true}
wheel3_motor_shaft_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel3_motor_shaft_joint
  pid: {p: 0.05,i: 0.0,d: 0.0001, i_clamp: 1.0, antiwindup: true}
