# 
# parameter file for amcl
# 

# 10 mm
#update_min_d : 0.01
# pi / 32
#update_min_a : 0.1

update_min_d : 0.2
update_min_a : 0.2
resample_interval : 2
use_map_topic : false
gui_publish_rate : -1.0
save_pose_rate : 0.5
laser_max_beams : 30
min_particles : 500
max_particles : 5000
kld_err : 0.05
kld_z : 0.99
recovery_alpha_slow : 0.001
recovery_alpha_fast : 0.1
transform_tolerance : 2.0

laser_z_hit : 0.95
laser_z_short : 0.05
laser_z_max : 0.05
laser_z_rand : 0.05
laser_sigma_hit : 0.2
laser_lambda_short : 0.1
laser_model_type : likelihood_field
#laser_model_type : beam
laser_likelihood_max_dist : 2.0

odom_model_type : omni-corrected
# alpha1: Specifies the expected noise in odometry's rotation estimate from the rotational component of the robot's motion.
odom_alpha1 : 0.05
# alpha2: Specifies the expected noise in odometry's rotation estimate from translational component of the robot's motion.
odom_alpha2 : 0.02
# alpha3: Specifies the expected noise in odometry's translation estimate from the translational component of the robot's motion.
odom_alpha3 : 0.010
# alpha4: Specifies the expected noise in odometry's translation estimate from the rotational component of the robot's motion.
odom_alpha4 : 0.005
# alpha5: Translation-related noise parameter (only used if model is "omni").
odom_alpha5 : 0.003