#Overall filter parameters
min_particles : 500 #パーティクルの数の範囲　パーティクルの数は分散に応じて可変
max_particles : 5000
kld_err : 0.05
kld_z : 0.99
update_min_d : 0.2 #Translational movement required before performing a filter update. [m]
update_min_a : 0.5 #Rotational movement required before performing a filter update. [rad]
resample_interval : 1
transform_tolerance : 0.5
recovery_alpha_slow : 0.001
recovery_alpha_fast : 0.1
initial_cov_xx : 0.025 
initial_cov_yy : 0.025
initial_cov_aa : 0.068
gui_publish_rate : -1.0
save_pose_rate : -1.0
use_map_topic : true
first_map_only : true #When set to true, AMCL will only use the first map it subscribes to, rather than updating each time a new one is received.


#Laser model parameters
laser_min_range: -1.0
laser_max_range: -1.0
laser_max_beams: 30
laser_z_hit: 0.95 
laser_z_short: 0.05 
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_model_type: likelihood_field

#Odometry model parameters
odom_model_type : omni-corrected
# alpha1: Specifies the expected noise in odometry's rotation estimate from the rotational component of the robot's motion.
odom_alpha1 : 0.15
# alpha2: Specifies the expected noise in odometry's rotation estimate from translational component of the robot's motion.
odom_alpha2 : 0.05
# alpha3: Specifies the expected noise in odometry's translation estimate from the translational component of the robot's motion.
odom_alpha3 : 0.03
# alpha4: Specifies the expected noise in odometry's translation estimate from the rotational component of the robot's motion.
odom_alpha4 : 0.01
# alpha5: Translation-related noise parameter (only used if model is "omni").
odom_alpha5 : 0.2
