
obstacle_range: 3.5
raytrace_range: 4.0
footprint: [[-0.2, -0.12], [-0.2, 0.12], [0.05, 0.12], [0.05, -0.12]]
#robot_radius: ir_of_robot
inflation_radius: 0.55  #障害物までの距離がinflation_radius以下の場所をロボットの中心が絶対に通らないようにします。　

global_frame: 4omni/map
robot_base_frame: 4omni/base_link
update_frequency: 2.0
