map_update_interval : 5.0 #マップをアップデートする頻度[s]
inverted_laser : "false" #スキャンの方向　反時計回りならfalse 時計回りならtrue
transform_publish_period : 0.05 #tf(map->odom)をpublishする頻度[s]


#LiDAR
maxUrange : 30.0 #mappingを行なうのに使われるscanの最大検出距離
maxRange : 30.0 #実際のscanの最大検出距離
sigma : 0.05
kernelSize : 1
lstep : 0.05
astep : 0.05
iterations : 5
lsigma : 0.075
ogain : 3.0
lskip : 0 #Number of beams to skip in each scan. Take only every (n+1)th laser ray for computing a match (0 = take all rays)
minimumScore : 50.0 #Minimum score for considering the outcome of the scan matching good.

#Odometry
srr : 0.1 #オドメトリの誤差．平行移動に起因する平行移動の誤差．
srt : 0.2 #オドメトリの誤差．回転移動に起因する平行移動の誤差．
str : 0.1 #オドメトリの誤差．平行移動に起因する回転移動の誤差．
stt : 0.2 #オドメトリの誤差．回転移動に起因する回転移動の誤差．


#particle filter
##同一箇所で何度も観測を行なうと，パーティクルの尤度に偏りが生じてしまうため，一定距離以上移動した後に次の観測を行なう
linearUpdate : 1.0 #並行移動での観測の間隔[m]．
angularUpdate : 0.5 #角度方向の観測の間隔[rad]．
temporalUpdate : 3.0 
#観測の時間の間隔[sec]．
#上記のlinearUpdate，angularUpdate分ロボットが動いていなくとも，この時間経過したら観測を行なう．
#マイナスにセットすると，時間基準での観測は行わない．
resampleThreshold : 0.5 #パーティクルフィルタのリサンプリングの閾値．Neff
particles : 100 #パーティクルの数．amclはパーティクル数が分散に応じて可変であったが，gmappingでは固定．


#map
xmin : -50.0 #マップのサイズ
ymin : -50.0
xmax : 50.0
ymax : 50.0
delta : 0.05 #マップの分解能　グリッド一辺の長さ[m]
occ_thresh : 0.25 #グリッドセルで表現された各セルの値がこの値以上であれば障害物であると判断する．


#尤度場
llsamplerange : 0.01
llsamplestep : 0.01
lasamplerange : 0.005
lasamplestep : 0.005
