UselessPlanner:

# Robot Configuration Parameters - TR

  vel_lim_lin: 1.00 # choose slightly less than the base's capability
  
  # 遅い？
  # 回転角速度の最大値を上げるとき，k_angを適度に小さくしなきゃいけないと思う
  vel_lim_ang: 1.25
  
#  acc_lim_lin: 2.0 # maximum is theoretically 2.0, but we 
#  acc_lim_ang: 1.5
  
  #acc_lim_lin: 2.00 # maximum is theoretically 3.0.
  acc_lim_lin: 2.00 # maximum is theoretically 3.0.
  # OR 2.5
  
  dec_lim_lin: 3.50
  
  acc_lim_ang: 2.00
  dec_lim_ang: 3.00
  
  jerk_lim_lin: 0.2
  jerk_lim_ang: 0.4
  
  manual_k_lin: false
#  base_vel_k_lin: 1.5
#  base_vel_k_ang: 1.5

  base_vel_k_tan: 1.40
  base_vel_k_nor: 1.50
  # 4/1の撮影はk_ang = 2.50でやった
  #base_vel_k_ang: 1.75
  base_vel_k_ang: 1.00

# Goal Tolerance Parameters
  goal_tolerance_ang: 0.025   # in radian? previously 0.3
  goal_tolerance_lin: 0.025   # in metre,  previously 0.15
  #wp_tolerance_lin: 1.25      # trans waypoint tolerance in metre
  #粒度が荒い時は0.75で十分なのだけど，粒度を上げると遅くてかなわん
  wp_tolerance_lin: 2.00     # trans waypoint tolerance in metre

  #tan_half_value_diff_nor: -1.0
  tan_half_value_diff_nor: 0.200
  rot_half_value_diff_nor: 0.050
  #rot_half_value_diff_tan: 4.000
  rot_half_value_diff_tan: -1.00

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: odom

# Omni-drive robot configuration
  holonomic_robot: true
  
  