motor_max_acc : 1000
motor_max_vel : 1000
invert_x : true
invert_y : false
invert_z : false
robot_radius : 0.412579
wheel_radius : 0.0508

# motor_max_vel = MVL(1600) / KRF(20) = 80
#
#
#motor_max_acc = motor_torque * 2 / (mass * wheel_radius)
#
#MTQ(0.172)*20*4/(10*0.0508)
#