TrajectoryPlannerROS:
  min_vel_x: 0.1
  min_in_place_vel_theta: 0.4
  holonomic_robot: true #ホロノミックなロボットかどうか。全方位移動車両の場合にはtrueにする。差動二輪やステアリング型の場合はfalse。
  meter_scoring: true
  controller_frequency: 10.0
