
acc_lim_x: 2.5 
acc_lim_y: 2.5 
acc_lim_th: 3.2 


max_trans_vel: 10.0 
min_trans_vel: 0.1 

max_vel_x: 10.0
min_vel_x: -10.0

max_vel_y: 10.0
min_vel_y: -10.0 

max_rot_vel: 1.0 
min_rot_vel: 0.4
 
yaw_goal_tolerance: 0.01
xy_goal_tolerance: 0.2 
latch_xy_goal_tolerance: true

sim_time: 1.7 
sim_granularity: 0.2 
vx_samples: 10 
vy_samples: 10 
vth_samples: 20 

goal_distance_bias: 32.0 
path_distance_bias: 24.0 
occdist_scale: 0.03
forward_point_distance: 0.325 
stop_time_buffer: 0.2 
scaling_speed: 0.25 
max_scaling_factor: 0.2 
publish_cost_grid : false

oscillation_reset_dist: 0.05 

prune_plan : true
