!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  acc_lim_theta: 3.2
  acc_lim_x: 7.6
  acc_lim_y: 7.6
  acc_limit_trans: 4.473742829211556
  angular_sim_granularity: 0.1
  forward_point_distance: 0.325
  goal_distance_bias: 1.633123935319537e+16
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      acc_lim_theta: 3.2
      acc_lim_x: 7.6
      acc_lim_y: 7.6
      acc_limit_trans: 4.473742829211556
      angular_sim_granularity: 0.1
      forward_point_distance: 0.325
      goal_distance_bias: 1.633123935319537e+16
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      max_rot_vel: 1.1342773492554057
      max_scaling_factor: 0.2
      max_trans_vel: 31.820515953774077
      max_vel_x: 15.894544843865322
      max_vel_y: 1.633123935319537e+16
      min_rot_vel: 0.4
      min_trans_vel: 0.0
      min_vel_x: -1.633123935319537e+16
      min_vel_y: -1.633123935319537e+16
      name: Default
      occdist_scale: 0.01
      oscillation_reset_angle: 0.2
      oscillation_reset_dist: 0.05
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      path_distance_bias: 32.0
      prune_plan: true
      restore_defaults: false
      rot_stopped_vel: 0.1
      scaling_speed: 0.25
      sim_granularity: 0.025
      sim_time: 7.915815088305826
      state: true
      stop_time_buffer: 0.2
      trans_stopped_vel: 0.1
      twirling_scale: 0.0
      type: ''
      use_dwa: true
      vth_samples: 20
      vx_samples: 3
      vy_samples: 10
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.1
    state: []
  max_rot_vel: 1.1342773492554057
  max_scaling_factor: 0.2
  max_trans_vel: 31.820515953774077
  max_vel_x: 15.894544843865322
  max_vel_y: 1.633123935319537e+16
  min_rot_vel: 0.4
  min_trans_vel: 0.0
  min_vel_x: -1.633123935319537e+16
  min_vel_y: -1.633123935319537e+16
  occdist_scale: 0.01
  oscillation_reset_angle: 0.2
  oscillation_reset_dist: 0.05
  path_distance_bias: 32.0
  prune_plan: true
  restore_defaults: false
  rot_stopped_vel: 0.1
  scaling_speed: 0.25
  sim_granularity: 0.025
  sim_time: 7.915815088305826
  stop_time_buffer: 0.2
  trans_stopped_vel: 0.1
  twirling_scale: 0.0
  use_dwa: true
  vth_samples: 20
  vx_samples: 3
  vy_samples: 10
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
state: []
