controller_frequency: 10.0
planner_patience: 0.5
controller_patience: 3.0
planner_frequency: 0.0
shutdown_costmaps: true 
oscillation_timeout: 10.0
oscillation_distance: 0.2

#recovery_behavior_enabled: false
