ButtonA: 1 #O
ButtonB: 0 #X
ButtonX: 2 #Δ
ButtonY: 3 #□
ButtonLB: 4
ButtonRB: 5
ButtonSelect: 8 #share
ButtonStart: 10 #logo
ButtonLeftThumb: 11
ButtonRightThumb: 12
AxisLeftThumbX: 0
AxisLeftThumbY: 1
AxisRightThumbX: 3
AxisRightThumbY: 4
AxisLeftTrigger: 6
AxisRightTrigger: 7
