tasks : 
  ButtonA: Pass #O
  # ButtonB: 3 #X
  # ButtonX: 1 #Δ
  # ButtonY: 0 #□
  ButtonLB: Enable
  ButtonRB: Disable
  # ButtonSelect: 8 #share
  # ButtonStart: 10 #logo
  # ButtonLeftThumb: 12
  # ButtonRightThumb: 13
  # AxisLeftThumbX: 0
  # AxisLeftThumbY: 1
  # AxisRightThumbX: 2
  # AxisRightThumbY: 3
  # AxisLeftTrigger: 4
  # AxisRightTrigger: 5